package com.bluesky.groovier.api;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;

import com.bluesky.groovier.event.GroovierEventManager;
import com.bluesky.groovier.hooks.GroovierHooks;
import com.bluesky.groovier.util.AtomicFiles;

import groovy.lang.Closure;
import net.neoforged.fml.loading.FMLPaths;

/**
 * 脚本钉子 API(绑定名 {@code Pins})—— 方法钉子(SPEC 6.3)的运行期两面。
 *
 * <p>两段式(与 Surgery 同构):<b>declare</b> 在运行期写钉子清单,下次启动由核心
 * 在类加载期(mixin 前)对目标方法做重命名包装、生成查询点;<b>override/on</b> 在
 * 运行期向覆盖表注册回调,对已钉方法立即生效(reload 按脚本注销重挂)。
 *
 * <p>脚本用法:
 * <pre>
 *   // 阶段一:声明钉子(下次启动生效;目标类须未被加载过才可钉)
 *   Pins.declare(name: "zombie-slow",
 *                target: "net.minecraft.world.entity.monster.Zombie",
 *                method: "serverAiStep")            // 可选 descriptor: "(J)V" 精确重载
 *
 *   // 阶段二:运行时覆盖(钉子注入后立即可用;未声明钉子前注册会被忽略)
 *   Pins.override("net.minecraft.world.entity.monster.Zombie.serverAiStep") { thiz, args -&gt;
 *       Log.info("overridden!")                      // 返回值 = 覆盖返回值(void 方法返回 null 即可)
 *   }
 *   Pins.on("net.minecraft.world.entity.monster.Zombie.serverAiStep") { thiz, args, result -&gt;
 *       Log.info("after run")                        // 伪事件:原方法实际执行后触发,仅观察
 *   }
 *   Pins.list()                                      // 清单 + 本轮注入状态 + 回调计数
 *   Pins.remove("zombie-slow")                       // 删除钉子包(下次启动不生效)
 * </pre>
 *
 * <p>产物:local/pins/&lt;name&gt;/pin.txt(行式 manifest)。
 * 注入状态见 local/mixin_invalidated/report.json 的 pins 块(冷启动后)。
 */
public final class PinsApi {

    public static final PinsApi INSTANCE = new PinsApi();

    private static final Path PINS = FMLPaths.GAMEDIR.get().resolve("local").resolve("pins");
    private static final Path REPORT = FMLPaths.GAMEDIR.get()
            .resolve("local").resolve("mixin_invalidated").resolve("report.json");

    private PinsApi() {}

    /**
     * 声明钉子(下次启动生效)。
     *
     * @param spec 命名参数:name(默认 target 短名 + "." + method)、target(必填,点分类名)、
     *             method(必填,命中全部同名重载)、descriptor(可选,精确单重载)、enabled(默认 true)
     * @return 摘要 Map(name/target/method/descriptor/location)
     */
    public Map<String, Object> declare(Map<String, Object> spec) {
        String target = str(spec.get("target"));
        String method = str(spec.get("method"));
        if (target == null || target.isBlank() || method == null || method.isBlank()) {
            throw new IllegalArgumentException("Pins.declare requires 'target' and 'method'");
        }
        // 包名/类名/方法名清洗:含路径分隔符、'..'、'<init>' 等非法成分直接报错,不做静默转换
        validateName(target, "target");
        validateName(method, "method");
        String descriptor = str(spec.get("descriptor"));
        boolean enabled = !"false".equals(str(spec.get("enabled")));
        String name = str(spec.get("name"));
        if (name == null || name.isBlank()) {
            String shortName = target.contains(".") ? target.substring(target.lastIndexOf('.') + 1) : target;
            name = shortName + "." + method;
        }
        validatePackName(name);

        Path dir = PINS.resolve(name);
        StringBuilder manifest = new StringBuilder();
        manifest.append("# groovier pin pack (regenerated by Pins.declare)\n");
        manifest.append("target=").append(target).append('\n');
        manifest.append("method=").append(method).append('\n');
        if (descriptor != null && !descriptor.isBlank()) {
            manifest.append("descriptor=").append(descriptor).append('\n');
        }
        manifest.append("enabled=").append(enabled).append('\n');
        try {
            Files.createDirectories(dir);
            // pin.txt 写后即被 coremod(PinStore/注入通道)读取,原子写
            AtomicFiles.writeString(dir.resolve("pin.txt"), manifest.toString());
        } catch (IOException e) {
            throw new IllegalStateException("Failed to write pin pack: " + dir, e);
        }
        GroovyLog.INSTANCE.info("Pin pack '{}' declared for {}.{} — takes effect on next launch",
                name, target, method);
        Map<String, Object> out = new LinkedHashMap<>();
        out.put("name", name);
        out.put("target", target);
        out.put("method", method);
        out.put("descriptor", descriptor);
        out.put("location", dir.toString());
        return out;
    }

    /**
     * 注册覆盖回调:方法入口查询点命中时,闭包返回值(基本类型自动装箱处理在核心侧)
     * 即方法返回值;返回 null 视为未覆盖。闭包参数 (thiz, args)。
     */
    public void override(String key, Closure<?> closure) {
        String script = ownerScript(closure);
        GroovierHooks.registerEnter(key, script, (thiz, args, result) -> {
            Object v = closure.call(thiz, args);
            // void 方法覆盖:闭包无返回 → null 会被视为"未覆盖",用 Groovy 空串语义区分不可行;
            // 约定:void 方法覆盖直接 return null 之外的任意值(如 true),包装侧丢弃该值
            return v;
        });
        GroovyLog.INSTANCE.info("Pin override registered for {} (script {})", key, script);
    }

    /** 注册后置伪事件回调:原方法实际执行后触发,参数 (thiz, args, result);override 命中时不触发。 */
    public void on(String key, Closure<?> closure) {
        String script = ownerScript(closure);
        GroovierHooks.registerExit(key, script, (thiz, args, result) -> {
            closure.call(thiz, args, result);
            return null;
        });
        GroovyLog.INSTANCE.info("Pin on-callback registered for {} (script {})", key, script);
    }

    /**
     * 钉子包清单:name -> {target/method/descriptor/enabled, 注入状态(report.json pins 块),
     * enter/exit 回调数(本轮运行期注册)}。
     */
    public Map<String, Map<String, String>> list() {
        Map<String, String> states = reportPins();
        Map<String, int[]> counts = GroovierHooks.counts();
        Map<String, Map<String, String>> out = new LinkedHashMap<>();
        for (Path dir : packDirs()) {
            String name = dir.getFileName().toString();
            Map<String, String> info = new LinkedHashMap<>();
            try {
                for (String raw : Files.readAllLines(dir.resolve("pin.txt"), StandardCharsets.UTF_8)) {
                    String line = raw.trim();
                    if (line.isEmpty() || line.startsWith("#")) {
                        continue;
                    }
                    int eq = line.indexOf('=');
                    if (eq > 0) {
                        info.put(line.substring(0, eq), line.substring(eq + 1));
                    }
                }
            } catch (IOException e) {
                info.put("error", "manifest unreadable: " + e);
            }
            String state = states.get(name);
            info.put("state", state == null ? "not applied this launch" : state);
            int[] c = counts.get(info.getOrDefault("target", "") + "." + info.getOrDefault("method", ""));
            if (c != null) {
                info.put("callbacks", "enter=" + c[0] + ", exit=" + c[1]);
            }
            out.put(name, info);
        }
        return out;
    }

    /** 删除钉子包(下次启动不生效);返回是否删除了存在的包。 */
    public boolean remove(String name) {
        if (name == null || name.isBlank() || !isSafePackName(name)) {
            GroovyLog.INSTANCE.error("Pins.remove({}): invalid pack name, ignored", name);
            return false;
        }
        Path dir = PINS.resolve(name);
        if (!Files.isDirectory(dir)) {
            return false;
        }
        try (Stream<Path> walk = Files.walk(dir)) {
            walk.sorted(java.util.Comparator.reverseOrder()).forEach(p -> {
                try {
                    Files.delete(p);
                } catch (IOException e) {
                    GroovyLog.INSTANCE.error("Pins.remove({}) failed to delete {}", name, p, e);
                }
            });
        } catch (IOException e) {
            GroovyLog.INSTANCE.error("Pins.remove({}) walk failed", name, e);
            return false;
        }
        GroovyLog.INSTANCE.info("Pin pack '{}' removed", name);
        return true;
    }

    private Map<String, String> reportPins() {
        Map<String, String> out = new LinkedHashMap<>();
        if (!Files.isRegularFile(REPORT)) {
            return out;
        }
        try {
            boolean in = false;
            for (String raw : Files.readAllLines(REPORT)) {
                String line = raw.trim();
                if (line.startsWith("\"pins\": {")) {
                    in = true;
                    continue;
                }
                if (in) {
                    // 块收尾行可能带缩进/逗号(overrides 块位于 pins 之后),按 trim 后判定
                    if (line.startsWith("}")) {
                        break;
                    }
                    String name = line.startsWith("\"") ? line.substring(1, Math.max(1, line.indexOf("\":"))) : null;
                    if (name == null || name.isBlank()) {
                        continue;
                    }
                    out.put(name, line.contains("error") ? "error" : "applied");
                }
            }
        } catch (IOException e) {
            GroovyLog.INSTANCE.error("Pins.list() report read failed: {}", e);
        }
        return out;
    }

    private java.util.List<Path> packDirs() {
        if (!Files.isDirectory(PINS)) {
            return java.util.List.of();
        }
        try (Stream<Path> stream = Files.list(PINS)) {
            return stream.filter(Files::isDirectory).sorted().toList();
        } catch (IOException e) {
            GroovyLog.INSTANCE.error("Pins.list() scan failed: {}", e);
            return java.util.List.of();
        }
    }

    /** 归属脚本:当前执行上下文优先,事件回调内注册经闭包 owner 链反查(与监听器同构)。 */
    private String ownerScript(Closure<?> closure) {
        String current = GroovierEventManager.INSTANCE.currentScript();
        if (!current.isEmpty()) {
            return current;
        }
        return GroovierEventManager.INSTANCE.resolveOwnerScript(closure);
    }

    private static String str(Object o) {
        return o == null ? null : o.toString();
    }

    /** 包名须可安全用作目录名(拒绝路径分隔符、'..'、控制字符等);非法即抛出 */
    private static void validatePackName(String name) {
        if (!isSafePackName(name)) {
            throw new IllegalArgumentException("Invalid pin pack name '" + name
                    + "': must not contain path separators, '..', ':', '<', '>' or control characters");
        }
    }

    /** 类名/方法名清洗:拒绝路径分隔符、'..'、'<init>' 等(泛化为 '<' '>' 任意尖括号成分) */
    private static void validateName(String value, String field) {
        if (value.contains("/") || value.contains("\\") || value.contains("..")
                || value.contains("<") || value.contains(">")) {
            throw new IllegalArgumentException("Invalid pin " + field + " '" + value
                    + "': must not contain path separators, '..', '<' or '>'");
        }
    }

    /** 目录名安全检查:无路径分隔符、无 '..'、无 Windows 保留字符与控制字符 */
    private static boolean isSafePackName(String name) {
        return name.matches("[^/\\\\:<>?\"|*\0-\u001f]+") && !name.contains("..");
    }
}
